ProyectoIdentity/Models/AccesoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ProyectoIdentity.Models
{
    public class AccesoViewModel
    {
        [Required(ErrorMessage = "El Email es obligatorio")]
        [EmailAddress]
        public string Email { get; set; }
        [Required(ErrorMessage = "La contraseña es obligatoria")]
        [StringLength(50, ErrorMessage = "El {0} debe estar entre al menos {2} caracteres de longitud", MinimumLength = 5)]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string Password { get; set; }
        [Display(Name = "Recordar datos")]
        public bool RememberMe { get; set; }
    }
}

ProyectoIdentity/Models/AppUsuario.cs
using Microsoft.AspNetCore.Identity;

namespace ProyectoIdentity.Models
{
    public class AppUsuario : IdentityUser
    {
        public string Nombre { get; set; }
        public string URL { get; set; }
        public Int32 CodigoPais { get; set; }
        public string Telefono { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public bool Estado { get; set; }
    }
}

ProyectoIdentity/Models/ErrorViewModel.cs
namespace ProyectoIdentity.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProyectoIdentity/Models/RegistroViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ProyectoIdentity.Models
{
    public class RegistroViewModel
    {
        [Required(ErrorMessage = "El Email es obligatorio")]
        [EmailAddress]
        public string Email { get; set; }
        [Required(ErrorMessage = "La contraseña es obligatoria")]
        [StringLength(50, ErrorMessage = "El {0} debe estar entre al menos {2} caracteres de longitud", MinimumLength = 5)]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string Password { get; set; }
        [Required(ErrorMessage = "La confirmación de contraseña es obligatoria")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirmación Contraseña")]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string Nombre { get; set; }
        public string URL { get; set; }
        public Int32 CodigoPais { get; set; }
        public string Telefono { get; set; }
        [Required(ErrorMessage = "El país es obligatorio")]
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        [Required(ErrorMessage = "La fecha de nacimiento es obligatoria")]
        public DateTime FechaNacimiento { get; set; }
        [Required(ErrorMessage = "El estado es obligatorio")]
        public bool Estado { get; set; }
    }
}

ProyectoIdentity/Controllers/CuentasController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProyectoIdentity.Models;

namespace ProyectoIdentity.Controllers
{
  public class CuentasController : Controller
  {
    private readonly UserManager<IdentityUser> _userManager;
    private readonly SignInManager<IdentityUser> _signInManager;
    public CuentasController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
    {
      userManager = _userManager;
      signInManager = _signInManager;
    }

    public IActionResult Index()
    {
      return View();
    }
    [HttpGet]
    public async Task<IActionResult> Registro()
    {
      RegistroViewModel registroVM = new RegistroViewModel();
      return View(registroVM);
    }
    [HttpPost]
    public async Task<IActionResult> Registro(RegistroViewModel rgViewModel)
    {
      if (ModelState.IsValid)
      {
        var usuario = new AppUsuario
        {
          UserName = rgViewModel.Email,
          Email = rgViewModel.Email,
          Nombre = rgViewModel.Nombre,
          URL = rgViewModel.URL,
          CodigoPais = rgViewModel.CodigoPais,
          Telefono = rgViewModel.Telefono,
          Pais = rgViewModel.Pais,
          Ciudad = rgViewModel.Ciudad,
          Direccion = rgViewModel.Direccion,
          FechaNacimiento = rgViewModel.FechaNacimiento,
          Estado = rgViewModel.Estado
        };
        var resultado = await _userManager.CreateAsync(usuario, rgViewModel.Password);
        if (resultado.Succeeded)
        {
          await _signInManager.SignInAsync(usuario, isPersistent: false);
          return RedirectToAction("Index", "Home");
        }
        ValidarErrores(resultado);
      }
      return View(rgViewModel);
    }
    private void ValidarErrores(IdentityResult resultado)
    {
      foreach (var error in resultado.Errors)
      {
        ModelState.AddModelError(String.Empty, error.Description);
      }
    }
  }
}

ProyectoIdentity/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoIdentity.Models;
using System.Diagnostics;

namespace ProyectoIdentity.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProyectoIdentity/Views/Cuentas/Registro.cshtml
@model RegistroViewModel

@{
  ViewData["Title"] = "Registro de usuario";
  Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Registro de usuario</h1>
<form asp-controller="Cuentas" asp-action="Registro" method="post" role="form">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="Nombre" class="col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="Nombre" class="form-control" />
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>
    </div>    
    <div class="form-group">
        <label asp-for="Email" class="col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
        <div class="form-group">
        <label asp-for="URL" class="col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="URL" class="form-control" />
            <span asp-validation-for="URL" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="CodigoPais" class="col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="CodigoPais" class="form-control" />
            <span asp-validation-for="CodigoPais" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Telefono" class="col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="Telefono" class="form-control" />
            <span asp-validation-for="Telefono" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Ciudad" class="col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="Ciudad" class="form-control" />
            <span asp-validation-for="Ciudad" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Ciudad" class="col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="Ciudad" class="form-control" />
            <span asp-validation-for="Ciudad" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Direccion" class="col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="Direccion" class="form-control" />
            <span asp-validation-for="Direccion" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="FechaNacimiento" class="col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="FechaNacimiento" class="form-control" />
            <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="ConfirmPassword" class="col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="ConfirmPassword" class="form-control"/>
            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <button type="submit" class="btn-success">Registrarse</button>
        </div>
    </div>
</form>
@section Scripts{
  @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
  }
}

ProyectoIdentity/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProyectoIdentity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoIdentity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoIdentity.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoIdentity</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <!-- Vista parcial para el acceso(login) y registro -->
                    <partial name="_LoginRegistroVistaParcial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProyectoIdentity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProyectoIdentity/Views/Shared/_LoginRegistroVistaParcial.cshtml
<ul class="navbar-nav ml-auto">
    <li class="nav-item">
        <a class="nav-link text-white" asp-area="" asp-controller="Cuentas" asp-action="Registro">Registro</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-white" asp-area="" asp-controller="Cuentas" asp-action="Acceso">Acceder</a>
    </li>
</ul>